services:
  api:
    build: .
    container_name: sector404-administration-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - sector404-network
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/myapp
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    networks:
      - sector404-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  sector404-network:
    driver: bridge